# Generated by Django 4.1.3 on 2022-11-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Pressure_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('pressure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BMI_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('height', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('BMI', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Health_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('currentMed', models.CharField(max_length=30)),
                ('pastMed', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('emergencyName', models.CharField(max_length=30)),
                ('emergencyPhone', models.CharField(max_length=20)),
                ('doctorName', models.CharField(max_length=30)),
                ('doctorPhone', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=50)),
            ],
        ),
    ]
